#!/bin/bash
# Manual Policy Control Script
# Allows you to manually force RL to specific mode for demonstration

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "============================================================"
echo "RL-QoS Manual Policy Control"
echo "============================================================"
echo ""
echo "Current implementation uses trained RL model"
echo ""
echo "To demonstrate different policies manually, use Mininet commands:"
echo ""
echo "In Mininet terminal:"
echo ""
echo "  # Priority to WORK traffic:"
echo "  mininet> sh ovs-ofctl add-flow s1 -O OpenFlow13 'in_port=1,actions=set_queue:0,normal'"
echo "  mininet> sh ovs-ofctl add-flow s1 -O OpenFlow13 'in_port=2,actions=set_queue:0,normal'"
echo "  mininet> sh ovs-ofctl add-flow s1 -O OpenFlow13 'in_port=3,actions=set_queue:2,normal'"
echo "  mininet> sh ovs-ofctl add-flow s1 -O OpenFlow13 'in_port=4,actions=set_queue:2,normal'"
echo ""
echo "  # Priority to ENTERTAINMENT traffic:"
echo "  mininet> sh ovs-ofctl add-flow s1 -O OpenFlow13 'in_port=1,actions=set_queue:2,normal'"
echo "  mininet> sh ovs-ofctl add-flow s1 -O OpenFlow13 'in_port=2,actions=set_queue:2,normal'"
echo "  mininet> sh ovs-ofctl add-flow s1 -O OpenFlow13 'in_port=3,actions=set_queue:0,normal'"
echo "  mininet> sh ovs-ofctl add-flow s1 -O OpenFlow13 'in_port=4,actions=set_queue:0,normal'"
echo ""
echo "  # BALANCED mode:"
echo "  mininet> sh ovs-ofctl add-flow s1 -O OpenFlow13 'in_port=1,actions=set_queue:1,normal'"
echo "  mininet> sh ovs-ofctl add-flow s1 -O OpenFlow13 'in_port=2,actions=set_queue:1,normal'"
echo "  mininet> sh ovs-ofctl add-flow s1 -O OpenFlow13 'in_port=3,actions=set_queue:1,normal'"
echo "  mininet> sh ovs-ofctl add-flow s1 -O OpenFlow13 'in_port=4,actions=set_queue:1,normal'"
echo ""
echo "  # View current flows:"
echo "  mininet> sh ovs-ofctl dump-flows s1 -O OpenFlow13"
echo ""
echo "  # Clear all flows (let RL take over again):"
echo "  mininet> sh ovs-ofctl del-flows s1"
echo ""
echo "============================================================"
echo "NOTE: RL controller will override these after 5 seconds"
echo "For pure manual control, stop the Ryu controller first"
echo "============================================================"
